##Vector

In [60]:
import numpy as np # numpy library for linear algebra

###How to create a vector?

In [61]:
asArray = np.array([1,2,3]) # 1D array
asArray

array([1, 2, 3])

In [62]:
# .shape is a method to find dimensions of matrix
asArray.shape

(3,)

### Row Vector

In [63]:
rowVec = np.array([ [1,2,3] ]) # row vector
rowVec

array([[1, 2, 3]])

In [64]:
rowVec.shape

(1, 3)

### Column Vector

In [65]:
colVec = np.array([ [1],[2],[3] ]) # column vector
colVec

array([[1],
       [2],
       [3]])

In [66]:
colVec.shape

(3, 1)

##Vector Arithemtic

In [67]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

###Vector Addition

In [68]:
v1+v2

array([5, 7, 9])

###Vector Multiplication

In [69]:
v1*v2       # componentwise multiplication

array([ 4, 10, 18])

In [70]:
v1@v2       # scalar product

32

In [71]:
np.cross(v1,v2)         # vector product

array([-3,  6, -3])

###Vector Division

In [72]:
v1/v2       # componentwise division

array([0.25, 0.4 , 0.5 ])

In [73]:
v2//v1      # quotient of componentwise division

array([4, 2, 2])

In [74]:
v2%v1       # remainder of componentwise division

array([0, 1, 0])

###Scalar Multiplication

In [75]:
2*v1

array([2, 4, 6])

In [76]:
v1/2

array([0.5, 1. , 1.5])

### Some more operations on vectors

In [77]:
2 + v1      # add 2 into every component of v1

array([3, 4, 5])

In [78]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
v1+v2

array([[5, 7, 9]])

In [79]:
v1*v2

array([[ 4, 10, 18]])

In [80]:
v1@v2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [81]:
v1.shape

(1, 3)

In [82]:
3 + v2

array([[7, 8, 9]])

In [83]:
v1 = np.array([[1],[2],[3]])
v2 = np.array([[4],[5],[6]])
v1+v2

array([[5],
       [7],
       [9]])

In [84]:
v1*v2

array([[ 4],
       [10],
       [18]])

In [85]:
2 - v1

array([[ 1],
       [ 0],
       [-1]])

In [86]:
v1@v2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [87]:
v2-3*v1

array([[ 1],
       [-1],
       [-3]])

### Check if two vectors are equal

In [88]:
v1 == v1  # componentwise check

array([[ True],
       [ True],
       [ True]])

In [89]:
(v1==v2).all() #check if v1 = v2

False

In [90]:
v3 = np.array([[1],[2],[3]])
(v1==v3).all()

True

In [91]:
v4 = np.array([[1],[1],[3]])
(v1==v4).all()

False

In [92]:
(v1==v4).any()

True

In [93]:
v1 = np.array([[1,1,3]])
v2 = np.array([[-1],[2],[4]])

In [94]:
v1@v2

array([[13]])

In [95]:
np.dot(v1,v2)

array([[13]])

In [96]:
v1

array([[1, 1, 3]])

###Functions on Vectors

In [97]:
np.sin(v1)

array([[0.84147098, 0.84147098, 0.14112001]])

In [98]:
np.sqrt(v1)

array([[1.        , 1.        , 1.73205081]])

In [99]:
np.exp(v1)

array([[ 2.71828183,  2.71828183, 20.08553692]])

###Unit Vector

In [100]:
np.linalg.norm(v1)

3.3166247903554

In [101]:
unit_v1 = v1/np.linalg.norm(v1)

In [102]:
unit_v1

array([[0.30151134, 0.30151134, 0.90453403]])

##Matrix

In [103]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
A = np.ones((2,3))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [105]:
B = np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Create a random matrix

In [106]:
C = np.random.rand(2,3)
C

array([[0.23300212, 0.95649188, 0.01285084],
       [0.35718074, 0.90785346, 0.31964725]])

In [107]:
D = np.random.randn(2,3)
D

array([[-2.57735358, -0.71913094, -1.17747891],
       [ 0.12569809, -0.27480706, -0.33829192]])

In [108]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [109]:
np.random.seed(10) # this will always give fixed set of random numbers
A = np.random.randint(0,10,(3,3))  #(min, max*, (m,n))
A

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9]])

###Matrix Arithmetic

In [110]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

In [111]:
A.shape

(2, 3)

In [112]:
B.shape

(3, 2)

In [113]:
AB = A@B
AB

array([[22, 28],
       [49, 64]])

In [114]:
A*B

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [115]:
v1 = np.array([1,2,3])
v1

array([1, 2, 3])

In [116]:
A@v1

array([14, 32])

In [117]:
v2 = np.array([[3],[4],[5]])
v2

array([[3],
       [4],
       [5]])

In [118]:
A@v2

array([[26],
       [62]])

In [119]:
B@v2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

###Transpose of a Matrix

In [120]:
AT = A.T
AT

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
A

array([[1, 2, 3],
       [4, 5, 6]])

###Determinant

In [123]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

0.0

###Rank

In [124]:
np.linalg.matrix_rank(A)

2

###Inverse

In [125]:
A = np.array([[1,2],[3,4]])

In [126]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Elementary Operations on Matrix

In [127]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [128]:
A[0] #1st row of matrix

array([1, 2, 3])

In [129]:
A[1]-4*A[0]

array([ 0, -3, -6])

In [130]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
A[1] = A[1]-4*A[0]
A

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [132]:
A[2] = A[2] - 7*A[0]
A[3] = A[3] - 10*A[0]
A

array([[  1,   2,   3],
       [  0,  -3,  -6],
       [  0,  -6, -12],
       [  0,  -9, -18]])

## Convert A to its Row Echelon Form

In [133]:
A[2] = A[2]-2*A[1]
A[3] = A[3]-3*A[1]
A

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [134]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
import sympy as sp
A = sp.Matrix(A)
A

Matrix([
[ 1,  2,  3],
[ 4,  5,  6],
[ 7,  8,  9],
[10, 11, 12]])

In [136]:
rref_A = A.rref()
rref_A

(Matrix([
 [1, 0, -1],
 [0, 1,  2],
 [0, 0,  0],
 [0, 0,  0]]),
 (0, 1))

In [137]:
rref_A[0]

Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0],
[0, 0,  0]])

In [138]:
rref_A[1]

(0, 1)

###Rank

In [139]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [140]:
np.linalg.matrix_rank(A)

2

In [141]:
import scipy
scipy.linalg.null_space(A)

array([[-0.40824829],
       [ 0.81649658],
       [-0.40824829]])