In [1]:
import numpy as np

##Matrix

In [2]:
# create a random matrix of order order 5 x 5
np.random.seed(24)
A = np.random.randint(0,10,(5,5))
A

array([[2, 3, 0, 7, 1],
       [1, 1, 4, 4, 3],
       [2, 3, 3, 7, 9],
       [2, 7, 7, 9, 3],
       [0, 1, 1, 7, 6]])

In [3]:
A[2:5,1:5] # Slice of a matrix

array([[3, 3, 7, 9],
       [7, 7, 9, 3],
       [1, 1, 7, 6]])

In [4]:
A[2:,1:]

array([[3, 3, 7, 9],
       [7, 7, 9, 3],
       [1, 1, 7, 6]])

In [5]:
# element of position 2,3
A[2,3]

7

### Using sympy library

In [6]:
import sympy as sp
B = sp.Matrix(A)
B

Matrix([
[2, 3, 0, 7, 1],
[1, 1, 4, 4, 3],
[2, 3, 3, 7, 9],
[2, 7, 7, 9, 3],
[0, 1, 1, 7, 6]])

##QR Decomposition

In [7]:
np.random.seed(2)
A = np.random.randint(0,10,(5,5))
sp.Matrix(A)

Matrix([
[8, 8, 6, 2, 8],
[7, 2, 1, 5, 4],
[4, 5, 7, 3, 6],
[4, 3, 7, 6, 1],
[3, 5, 8, 4, 6]])

In [8]:
np.linalg.qr(A,'complete')

QRResult(Q=array([[-0.64465837,  0.29810252,  0.58999465,  0.09380244, -0.37236795],
       [-0.56407607, -0.72855229, -0.02135255, -0.25047151,  0.29637449],
       [-0.32232919,  0.34692966, -0.18534012,  0.53287385,  0.67634178],
       [-0.32232919, -0.04882714, -0.71763544,  0.28167869, -0.5471529 ],
       [-0.24174689,  0.50754524, -0.31952903, -0.75177636,  0.12918888]]), R=array([[-12.40967365, -10.07278705, -10.87861001,  -7.97764734,
        -11.1203569 ],
       [  0.        ,   5.05360871,   7.20714246,  -0.26854926,
          4.54863332],
       [  0.        ,   0.        ,  -5.35844584,  -5.06672257,
          0.88769663],
       [  0.        ,   0.        ,   0.        ,  -0.78316445,
         -1.28320292],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          2.49258545]]))

In [9]:
Q,R = np.linalg.qr(A,'complete')

In [10]:
sp.Matrix(Q)

Matrix([
[-0.644658371220304,   0.298102522694355,    0.58999464722465, 0.0938024411580939, -0.372367947946502],
[-0.564076074817766,  -0.728552286067671, -0.0213525487575272, -0.250471513564862,  0.296374489181909],
[-0.322329185610152,   0.346929660032224,  -0.185340123215336,  0.532873848468977,  0.676341783004871],
[-0.322329185610152, -0.0488271373378686,  -0.717635438686313,  0.281678690227872, -0.547152903105064],
[-0.241746889207614,   0.507545243380476,  -0.319529029629306, -0.751776363032706,  0.129188879899806]])

In [11]:
sp.Matrix(np.linalg.inv(Q))

Matrix([
[-0.644658371220304,  -0.564076074817766, -0.322329185610152,  -0.322329185610152, -0.241746889207614],
[ 0.298102522694355,   -0.72855228606767,  0.346929660032224, -0.0488271373378685,  0.507545243380476],
[  0.58999464722465, -0.0213525487575272, -0.185340123215336,  -0.717635438686312, -0.319529029629306],
[ 0.093802441158094,  -0.250471513564862,  0.532873848468976,   0.281678690227872, -0.751776363032706],
[-0.372367947946502,    0.29637448918191,  0.676341783004871,  -0.547152903105064,  0.129188879899806]])

In [12]:
sp.Matrix(R)

Matrix([
[-12.4096736459909, -10.0727870503173, -10.8786100143426,  -7.97764734385126, -11.1203569035502],
[                0,   5.0536087144694,  7.20714245600276, -0.268549255358276,  4.54863332042249],
[                0,                 0, -5.35844583575561,  -5.06672256961944, 0.887696627012929],
[                0,                 0,                 0, -0.783164450864778,  -1.2832029221492],
[                0,                 0,                 0,                  0,  2.49258544747862]])

In [13]:
sp.Matrix(np.round(R,3)) #round upto 3rd decimal place

Matrix([
[-12.41, -10.073, -10.879, -7.978, -11.12],
[     0,   5.054,   7.207, -0.269,  4.549],
[     0,       0,  -5.358, -5.067,  0.888],
[     0,       0,       0, -0.783, -1.283],
[     0,       0,       0,      0,  2.493]])

In [14]:
sp.Matrix(np.linalg.inv(R))

Matrix([
[-0.080582296402538, -0.160615583348252, -0.0524323697268167,  1.21513509479002,   0.57782831146004],
[                 0,  0.197878398685046,   0.266147657735488, -1.78970896772754,  -1.37724242768367],
[                 0,                  0,  -0.186621276140787,   1.2073559145204,  0.688018826668699],
[                 0,                  0,                   0, -1.27687103123206, -0.657343418313723],
[                 0,                  0,                   0,                 0,  0.401189857307219]])

In [15]:
Q@R

array([[8., 8., 6., 2., 8.],
       [7., 2., 1., 5., 4.],
       [4., 5., 7., 3., 6.],
       [4., 3., 7., 6., 1.],
       [3., 5., 8., 4., 6.]])

###LU Decomposition

In [16]:
import scipy.linalg # LU in scipy library
A = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
scipy.linalg.lu(A)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.14285714, 1.        , 0.        ],
        [0.57142857, 0.5       , 1.        ]]),
 array([[7.        , 8.        , 9.        ],
        [0.        , 0.85714286, 1.71428571],
        [0.        , 0.        , 0.        ]]))

In [17]:
P = scipy.linalg.lu(A)[0]
sp.Matrix(P)

Matrix([
[  0, 1.0,   0],
[  0,   0, 1.0],
[1.0,   0,   0]])

In [18]:
L = scipy.linalg.lu(A)[1]
sp.Matrix(L)

Matrix([
[              1.0,   0,   0],
[0.142857142857143, 1.0,   0],
[0.571428571428571, 0.5, 1.0]])

In [19]:
U= scipy.linalg.lu(A)[2]
sp.Matrix(U)

Matrix([
[7.0,               8.0,              9.0],
[  0, 0.857142857142857, 1.71428571428571],
[  0,                 0,                0]])

In [20]:
P@L@U

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

##Eigenvalues and Eigenvectors

In [21]:
A = np.array([[4,6,6],[1,3,2],[-1,-4,-3]])

In [22]:
np.linalg.eig(A)

EigResult(eigenvalues=array([ 4.,  1., -1.]), eigenvectors=array([[-9.04534034e-01,  7.53175883e-16, -6.35998728e-01],
       [-3.01511345e-01,  7.07106781e-01, -2.11999576e-01],
       [ 3.01511345e-01, -7.07106781e-01,  7.41998516e-01]]))

In [23]:
evals, evecs = np.linalg.eig(A)

In [24]:
evals

array([ 4.,  1., -1.])

In [25]:
evecs # eigenvectors are columns

array([[-9.04534034e-01,  7.53175883e-16, -6.35998728e-01],
       [-3.01511345e-01,  7.07106781e-01, -2.11999576e-01],
       [ 3.01511345e-01, -7.07106781e-01,  7.41998516e-01]])

In [26]:
v1 = evecs[:,0:1]
v1

array([[-0.90453403],
       [-0.30151134],
       [ 0.30151134]])

In [27]:
A@v1

array([[-3.61813613],
       [-1.20604538],
       [ 1.20604538]])

In [28]:
evals[0]*v1

array([[-3.61813613],
       [-1.20604538],
       [ 1.20604538]])

###Take transpose of eigenvector matrix

In [29]:
evecsT = np.transpose(evecs)
evecsT

array([[-9.04534034e-01, -3.01511345e-01,  3.01511345e-01],
       [ 7.53175883e-16,  7.07106781e-01, -7.07106781e-01],
       [-6.35998728e-01, -2.11999576e-01,  7.41998516e-01]])

In [30]:
evecsT[0]

array([-0.90453403, -0.30151134,  0.30151134])

In [31]:
evecsT[0].reshape(3,1) # reshape a matrix or vector

array([[-0.90453403],
       [-0.30151134],
       [ 0.30151134]])

In [32]:
evecsT[0].reshape(-1,1)

array([[-0.90453403],
       [-0.30151134],
       [ 0.30151134]])

In [33]:
B = np.array([[-2,2,-3],[2,1,-6],[-1,-2,0]])
B

array([[-2,  2, -3],
       [ 2,  1, -6],
       [-1, -2,  0]])

In [34]:
evals, evecs = np.linalg.eig(B)

In [35]:
evals

array([-3.,  5., -3.])

In [36]:
evecs

array([[-0.95257934,  0.40824829,  0.06498304],
       [ 0.27216553,  0.81649658,  0.82015882],
       [-0.13608276, -0.40824829,  0.56843356]])

##Singular Value Decomposition (SVD)

In [37]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,-1,1,-1],[2,1,-5,1]])
sp.Matrix(A)

Matrix([
[1,  2,  3,  4],
[5,  6,  7,  8],
[9, 10, 11, 12],
[1, -1,  1, -1],
[2,  1, -5,  1]])

In [38]:
# Singular-value decomposition
U,s,Vt = np.linalg.svd(A)

In [39]:
sp.Matrix(np.round(U))

Matrix([
[   0,   0,  1.0, -1.0,   0],
[-1.0,   0,    0,    0, 1.0],
[-1.0,   0,    0,    0,   0],
[   0,   0, -1.0, -1.0,   0],
[   0, 1.0,    0,    0,   0]])

In [40]:
s

array([25.44933905,  5.62480349,  2.2250472 ,  0.86133195])

In [41]:
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
sp.Matrix(Sigma)

Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

In [42]:
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[0]] = np.diag(s)
sp.Matrix(Sigma)

Matrix([
[25.4493390475816,                0,                0,                 0],
[               0, 5.62480348800967,                0,                 0],
[               0,                0, 2.22504719724239,                 0],
[               0,                0,                0, 0.861331952591945],
[               0,                0,                0,                 0]])

In [43]:
sp.Matrix(Vt)

Matrix([
[-0.400530105792676, -0.463207179517009,  -0.531396842311895, -0.585347878768304],
[ 0.395505741231602,  0.277913448419175,  -0.833869369497979,  0.266460500738191],
[-0.792323819441682,  0.125754391548074,  -0.149170612594286,  0.578063081756623],
[-0.235316400091225,  0.832099187019212, 0.00523439893748728, -0.502204874406687]])

In [44]:
#Verification of SVD
U@Sigma@Vt

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [ 1., -1.,  1., -1.],
       [ 2.,  1., -5.,  1.]])

##Principal Component Analysis (PCA)
### Low Rank Approximation

###Rank two approximation

In [45]:
np.linalg.matrix_rank(A)

4

In [46]:
U1 = U[:,:3] # Choose all rows and first k columns
U1

array([[-0.20678441, -0.08612451,  0.59501005],
       [-0.51806668, -0.01073676,  0.1677347 ],
       [-0.82934895,  0.06465099, -0.25954066],
       [ 0.00458276, -0.17471501, -0.73945034],
       [ 0.03172455,  0.97865326, -0.06066258]])

In [47]:
Sigma1 = Sigma[:3,:3] # Choose first k rows and k columns
Sigma1

array([[25.44933905,  0.        ,  0.        ],
       [ 0.        ,  5.62480349,  0.        ],
       [ 0.        ,  0.        ,  2.2250472 ]])

In [48]:
Vt1 = Vt[:3,:] # Choose first k rows and all columns

In [49]:
A1 = U1@Sigma1@Vt1
sp.Matrix(A1)

Matrix([
[0.867226409393741,   2.46949892467444,  3.00295342756105,  3.71663877073978],
[ 4.96117630466281,   6.13728395179698,  7.00086359773286,  7.91714368810138],
[ 9.05512619993187,   9.80506897891951,  10.9987737679047,   12.117648605463],
[0.868228389708168, -0.534044164565078,   1.0029311394218, -1.28122283432571],
[ 1.96072322617771,   1.13888607659133, -4.99912632394902, 0.916176742220781]])

In [50]:
sp.Matrix(A)

Matrix([
[1,  2,  3,  4],
[5,  6,  7,  8],
[9, 10, 11, 12],
[1, -1,  1, -1],
[2,  1, -5,  1]])

In [51]:
np.linalg.norm(A-A1)

0.8613319525919458

Find rank 2 approximation

In [52]:
k = 1

Uk = U[:,:k] # Choose all rows and first k columns
Sigmak = Sigma[:k,:k] # Choose first k rows and k columns
Vtk = Vt[:k,:] # Choose first k rows and all columns
Ak = Uk@Sigmak@Vtk
sp.Matrix(Ak)

Matrix([
[   2.10780029851962,    2.43764006036481,   2.79648996831508,    3.08040872773819],
[   5.28077096867895,    6.10713399742099,   7.00617750611952,    7.71749249325464],
[   8.45374163883828,    9.77662793447717,    11.215865043924,    12.3545762587711],
[-0.0467130693090933, -0.0540229779692213, -0.061975809474851, -0.0682680168990545],
[ -0.323375567628341,  -0.373979090309307, -0.429033306194131,  -0.472591697400957]])

In [53]:
np.linalg.norm(A-Ak)

6.1099216067997